### DISCUSSION TITLE
Configuration for Huawei Inverter

### DISCUSSION THREAD

**Discussion by karliwalti** [marq24/ha-goecharger-api2#1] [Show and tell]
I will post first discussion entry as token of appreciation. Thank you very much for making this integration. I installed it today and it works out of the box.
I use it in combination with the Huawei SUN inverter and the huawei_solar integration https://github.com/wlcrs/huawei_solar/. there the virtual grid sensor is inverted, so I changed the configuration to:

` pgrid: "{{states('sensor.power_meter_active_power') | float * -1}}"`

I havent tested the optional parameters  for inverter input and battery. Without, it already works fine. Some more testing needed to see how battery charging will behave in low and high PV production situations.

**Comment by marq24** [comment]
thanks - I have just added this info to the readme.md...

**Comment by ptc** [comment]
> 
> ` pgrid: "{{states('sensor.power_meter_active_power') | float * -1}}"`
> 
> I havent tested the optional parameters for inverter input and battery. Without, it already works fine. Some more testing needed to see how battery charging will behave in low and high PV production situations.

@karliwalti Does it work for you with inverter input and battery parameters set? In my case (also having a Sun2000 & Luna2000), after the battery is full, the charging starts but goes up to 11kWh, while discharging the luna2000 battery and taking additional energy from the grid.

**Reply by ptc** [reply]
I’ve noticed several issues, and I believe the go-e charger is at fault:
	•	The Huawei sensors are not real-time and update only every 30 seconds.
	•	The power consumption sensor updates every few seconds.
	•	The emulated controller updates every 5 seconds.

This leads to miscalculations. Also, when using three phases, it consumes three times the energy. When I force it to use only one phase, it somewhat works.

**Reply by karliwalti** [reply]
Hi @ptc 

I use it since almost a year without major issues. 
This is my setting:
```
alias: go-e PV surplus charging brigde
description: >-
  Simple automation to provide your go-eChargers with the required data so that
  the wallbox can support PV surplus charging.
mode: single
triggers:
  - seconds: /5
    trigger: time_pattern
conditions: []
actions:
  - data:
      pgrid: "{{states('sensor.spare_power_for_charging_car')}}"
      ppv: "{{states('sensor.inverter_input_power')}}"
      pakku: "{{0}}"
    action: goecharger_api2.set_pv_data
```

The Huawei solar plugin I kept at v 1.4.1 and did not update to 1.5.x
