### DISCUSSION TITLE
How do I turn on/off the charger

### DISCUSSION THREAD

**Discussion by Dennis3321** [marq24/ha-goecharger-api2#43] [Q&A]
Is there a way to totally disable/enable the charger via Home Assistant and this Api?

**Comment by marq24** [comment]
you can make use of the `select.goe_YOUR-SERIAL_trx` - but there is IMHO no way to physically disconnect the charger from power source...

as an alternative there is `select.goe_YOUR-SERIAL_frc` available to block charging

**Reply by Dennis3321** [reply]
My charger is on private property, but reachable from the public road. I'd like to have a simple switch in HA to turn it on/off, so others don't use my charger.

**Comment by marq24** [comment]
select.goe_YOUR-SERIAL_trx is the way to go then...

**Reply by marq24** [reply]
Just as additional info... My goe could also be reached from the public road — there is no gate or fence... 

You can configure the charger thats locked by default, and that you need to unlock it (trx) before usage... The unlock can happen via a rfid signal... or (and thats what I did) via an automation... as soon as my Ford MachE is connected to my charger the goe will be unlocked by setting trx.

**Reply by Dennis3321** [reply]
Sounds good, I have a BMW, and that also has a integration with HA. Care to share your details?/automation? Thnx

**Comment by marq24** [comment]
Here is "my" automation...

You need a trigger, that let you know, that "your vehicle" is now connected (or at the right place or what so ever) - as developer of the EVCC HA Integration I simply make use of an entity (`select.evcc_hh_7_vehicle_name`) that let me know, that my Ford is connected... it will change to my vehicle_id `ford_mach_e`

Probably you have something in your BMW Integration... And of course you need to enabled the "default" mode locked fr your Wallbox...

```yaml
alias: "[WB] AutoUnlock on MachE Connect"
description: "[WB] AutoUnlock on MachE Connect"
triggers:
  - entity_id:
      - select.evcc_hh_7_vehicle_name
    from: null
    to: ford_mach_e
    for:
      hours: 0
      minutes: 0
      seconds: 2
    trigger: state
conditions: []
actions:
  - metadata: {}
    data:
      option: "0"
    target:
      entity_id: select.goe_[YOUR_SERIAL_HERE]_trx
    action: select.select_option
mode: single
trace:
  stored_traces: 20
```
