### DISCUSSION TITLE
SMA SHM 2.0

### DISCUSSION THREAD

**Discussion by ckgth123** [marq24/ha-goecharger-api2#47] [General]
Hi,
for pgrid value:

```
`alias: go-e PV surplus charging brigde
description: >-
  Simple automation to provide your go-eChargers with the required data so that the wallbox can support PV surplus charging.
trigger:
  - platform: time_pattern
    seconds: /5
condition: []
action:
  - service: goecharger_api2.set_pv_data
    data:
      pgrid: "{{states('sensor.sunny_home_manager_2_metering_power_supplied')}}"
mode: single`
```

Will not work... Can you say what is the current sensor for Home Manager 2.0?
