### DISCUSSION TITLE
How to keep charging with minimal power when solar is too low to charge?

### DISCUSSION THREAD

**Discussion by AchWasss** [marq24/ha-goecharger-api2#48] [General]
Is there a way besides keeping  pgrid over 1200 W per automation to prevent charging stop using the API? 
I have a small pv. When its cloudy and my home battery starts charging, the power is not enough to allow charging on solar power only. So my charger stops charging. I would not care if it draws temporarily say up to 1kW, if it keeps charging.
Would be thankful for hints.

**Comment by drm5580** [comment]
Hi!

Ich schließe mich der Frage an bzw. hätte auch gerne die gleiche Funktion.
Also dass die WB nicht bei zu wenig Überschuss das Laden pausiert, sondern einfach mit Minimum (6A einphasig) weiterladet.

lg, Georg

**Comment by AchWasss** [comment]
My workaround within Home Assistant:

Automation:

alias: Audoh Überschussladen
description: >-
  Simple automation to provide your go-eChargers with the required data so that
  the wallbox can support PV surplus charging.
  https://github.com/marq24/ha-goecharger-api2 Only pgrid is nessesary. Negativ
  für vohandene Energie und Laden.
triggers:
  - seconds: /5
    trigger: time_pattern
conditions:
  - type: is_plugged_in
    condition: device
    device_id: GO-E API
    entity_id: CAR CONNECTED SENSOR
    domain: binary_sensor
    enabled: true
actions:
  - if:
      - condition: numeric_state
        entity_id: sensor.wolkigladen
        above: 1200
    then:
      - data:
          pgrid: "{{ (states('sensor.wolkigladen')|float(0)*-1) }}"
        action: goecharger_api2.set_pv_data
  - if:
      - condition: numeric_state
        entity_id: sensor.wolkigladen
        below: 1200
    then:
      - data:
          pgrid: "{{ (1200*-1) }}"
        action: goecharger_api2.set_pv_data
mode: single


Automation starts if car is connected.
The Wolkigladen sensor calculates the pv surplus

So if there is no pv surplus the car continuous get charged with 6A



Happv New Year all, Gutes Neues !

**Comment by marq24** [comment]
Ich kann hier wenig Inhaltlich beitragen - meiner Einschätzung nach, müsste das alles über irgendwelche Automatisierungen funktionieren - also die "Wenn _zu wenig_ PV Ertrag, dann starte das _manuelle_ Laden mit X" 

Oder halt einfacher "So zu tun, als wäre schlicht mehr PV Leistung verfügbar" ist sicherlich auch möglich - niemand zwinge Euch dem goeCharger die "Wahrheit" zu sagen. Und die Wallbox prüft auch sicherlich nicht, ob die Elektronen von Eurer PV oder aus dem Netz kommen.

**Reply by AchWasss** [reply]
War dann auch mein Gedanke…

**Comment by drm5580** [comment]
Sorry dass ich so lange nicht geantwortet habe! 
Hab das Thema über die Feiertage aus dem Augen verloren! 

Danke Achwass für deine Automation! 
Werde ich die Tage mal testen!

**Reply by AchWasss** [reply]
Next possibility would be calculate available power, don't push to the wallbox, but only change 

number.goe_259318_amp  ( charging current ) and
select.goe_259318_psm     ( phase count 3/1 ) and
select.goe_259318_lmo      ( wallbox mode default)

But then you relay only control on your own management.

**Comment by REK1803** [comment]
Ich hätte auch gerne, dass trotz zu wenig PV das Auto geladen wird. Das Script oben funktioniert bei mir nicht. Es sieht so aus, als ob sich der Blueprint mit diesem Script battlet und damit kein Mindeststrom gesetzt wird

**Reply by AchWasss** [reply]
Das ist meine Automation in Yaml:

"sensor.bitshake_smartmeterreader_m60_power"
Ist mein Smartmeter reader und muss ersetzt werden.

Damit das geht nur eine Automation zum Laden einschalten, damit sich nix stört.
( Neue Automation - in yaml bearbeiten - copy-paste, Sensoren anpassen, dann könnts klappen)

```
description: >- Überschussladen
  Simple automation to provide your go-eChargers with the required data so that
  the wallbox can support PV surplus charging.
  https://github.com/marq24/ha-goecharger-api2 Only pgrid is nessesary. Negativ
  für vohandene Energie und Laden.
mode: single
triggers:
  - seconds: /5
    trigger: time_pattern
conditions:
  - type: is_plugged_in
    condition: device
    device_id: baae10a8ac8a8c9d46e0a72eaa1e4813
    entity_id: 2bf2ea7727be25181d37ee0328c63f40
    domain: binary_sensor
    enabled: true
actions:
  - alias: Dont you dare to stop without BatteryCharge
    choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.aktuelle_pv_leistung
            below: 1400
            above: 1000
        sequence:
          - data:
              pgrid: "{{ -1200 }}"
            action: goecharger_api2.set_pv_data
            enabled: true
      - conditions:
          - condition: numeric_state
            entity_id: sensor.aktuelle_pv_leistung
            above: 1401
        sequence:
          - data:
              pgrid: >-
                {{ float(states('sensor.bitshake_smartmeterreader_m60_power'),0)
                }}
            action: goecharger_api2.set_pv_data
            enabled: true
  - if:
      - condition: state
        entity_id: switch.goe_259318_fup
        state:
          - "off"
    then:
      - type: turn_on
        device_id: baae10a8ac8a8c9d46e0a72eaa1e4813
        entity_id: ac7c9c85ea6fc39d50163ec458f9f507
        domain: switch
    enabled: true
    alias: Schalte PV-surplus an
```
Heisse Grüsse...
