### ISSUE TITLE
Surplus data with multiple goechargers

### ISSUE THREAD

**Issue by mr-gosh** [marq24/ha-goecharger-api2#13]
I created the automation for both of my goechargers but the data is only recieved by one of them (which one seems to change from reboot to reboot of the goechargers).

So the question is - how to configure that the pv surplus power usage is available to both chargers?
The distribution if both have a car connected could be configured through the "Lastmanegement" probably - but that is another question.

> your question is IMHO a bit "off topic" here... When you have two go-eChargers and have configured both in HA, and when you then use this integration to send your GRID-export data to both instances I would assume, that then __both__ chargers will try to consume this available energy... 

> IMHO (but I could be totally wrong) you have to distribute the available power "manually" to Charger1 and Charger2 (e.g. by simply divide the sensor data by 2)... Obviously only if both chargers have cars connected. I would kindly ask you to start a new discussion for your "dual" use case. - TIA

_Originally posted by @marq24 in https://github.com/marq24/ha-goecharger-api2/issues/11#issuecomment-2233684202_

The automation looks like this at the moment:

```
service: goecharger_api2.set_pv_data
data:
  pgrid: "{{states('sensor.smart_meter_summe_der_aktiven_momentanleistung')}}"
  ppv: "{{states('sensor.amperestoragepro_total_pv_power')}}"
  pakku: "{{states('sensor.amperestoragepro_battery_power|float*-1')}}"
```

For the Smartmeter readings I use the [EDL21 integration](https://www.home-assistant.io/integrations/edl21) and for the [AmpereStorage Battery an unofficial integration](https://github.com/dboeni/home-assistant-ampere-storage-pro).
